[package]
name = "ditto"
version = "0.1.0"
edition = "2021"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.8"

[dependencies]
lalrpop-util = {version = "0.19.8", features = ["lexer"]}
rand = "0.8.5"
regex = "1"
